### PR TITLE
issue #29

### PR DESCRIPTION
**Pull request by Major2001**
tried to solve issue 29

### CODE REVIEW

**Comment by irshadjsr21** [comment]
@rajatmw1999 This PR created a new model named `UserInfo`, but there is already a `User` model present. I think we should modify that `User` model instead of creating a new `UserInfo` model.

Affected issue: #40

**Comment by Major2001** [comment]
@rajatmw1999 Should I modify the existing Users model or the UserInfo model is ok?

**Comment by rajatmw1999** [comment]
@Major2001  the new user model is already modified. No need now..

**Comment by rajatmw1999** [comment]
@Major2001 Yes, please update the existing model with the provided information. Also, there are some conflicts right now, also resolve them.

**Pull request closed without merging**
