### PR TITLE
Added login/register functionality

### PR DESCRIPTION
**Pull request by sebasblancogonz**
I've implemented the login/register functionality as suggested. Express is used for routing and MongoDB for data management.
Few things to mention:

- I've created a **.env** file to store sensible data, such as DB url or the SECRET key used to create the login tokens.
- I didn't add comments on the code, if anything is not clear, just let me know I will add some clarifying comments.

Hope it works! Have a nice day!

### CODE REVIEW

**Comment by sebasblancogonz** [comment]
The **.env** file shouldn't be tracked on github, but I added it for development purposes.

**Comment by adavijit** [comment]
@sebasblancogonz  great work! looking forward to work with you :)

**Comment by sebasblancogonz** [comment]
Thank you so mucho @adavijit, have a great day

**Comment by adavijit** [comment]
@sebasblancogonz  added a new issue #6 
You may go with it :+1:

**Comment by sebasblancogonz** [comment]
> @sebasblancogonz added a new issue #6
> You may go with it 👍

I'll give it a try!

**Pull request merged**
