### PR TITLE
dark theme for blogman

### PR DESCRIPTION
**Pull request by anmolkaur18**
I have added two folders. One is in case for toggling option as it has js file.Second one only has html and css file.
Please review

### CODE REVIEW

**Comment by anmolkaur18** [comment]
https://codepen.io/anmolkaur18/pen/ExjbPMp

**Comment by rajatmw1999** [comment]
Please provide a screenshot of the pages you have made

**Comment by rajatmw1999** [comment]
Got it in code pen

**Comment by rajatmw1999** [comment]
I wanted you to make a complete page and give different colors to different types of texts, images and everything. This theme is going to be applied to blogman. It is just a h1 tag and a black background.

**Comment by anmolkaur18** [comment]
Can You please give me some sample text and images It would be helpful

**Comment by anmolkaur18** [comment]
right now I have created two text animations , one emoji hand, and two subtitle heading.

**Comment by anmolkaur18** [comment]
I am making new PR @rajatmw1999

**Pull request closed without merging**
