### PR TITLE
Modified login and signup page UI

### PR DESCRIPTION
**Pull request by lakshyajit165**
This is related to issue #20.
Here is how the modified pages look:
Screenshot from 2020-03-01 23-03-38
Screenshot from 2020-03-01 23-17-15
Screenshot from 2020-03-01 23-17-22

### CODE REVIEW

**Comment by adavijit** [comment]
Hey @lakshyajit165  go with the flow you can check it inside the readme.md file. 
@rajatmw1999  and @PrathamDogra  please dont accept PR if they dont do as per the flow

**Comment by rajatmw1999** [comment]
Hey @lakshyajit165 . Just have look at https://marvelapp.com/diceh34 . You have done a great job with these pages, just make changes according to the specified the link. Make this look like that..

**Comment by lakshyajit165** [comment]
Ok @rajatmw1999. I will make the changes. I just am not clear what meant by the flow. Because in the readme file it's given about those nom commands.(npm test, npm run build etc)

**Comment by rajatmw1999** [comment]
@lakshyajit165  By flow we mean that the pages that will show in order when the website is opened.. https://marvelapp.com/diceh34 . Have a look at this. When website opens, first page to appear should be the login page . OTherwis is user is not registered, then signup page, Then the blogs lists and then the particular blog.

https://marvelapp.com/diceh34 .
This flow is mentioned here.

You have worked on the login and signup UI. So, just make a PR for this UI. AND, update the routes in the back-end so, the flow works according to the above order. 
I hope you got it..

**Pull request merged**
