### PR TITLE
Added contributors component

### PR DESCRIPTION
**Pull request by simranaggarwal1999**
Fix to #100 
Added contributors component giving
List of contributors with their profile photo, user website url, username

### CODE REVIEW

**Comment by adavijit** [comment]
@simranaggarwal1999  post a Screenshot while raising a PR. Hope you have noticed the guidelines in Slack channel

**Comment by simranaggarwal1999** [comment]
Actually I just exported the Contributors component from its file. There was nothing to show up on console or browser that I added up. Thus I did not post the screenshot.

**Comment by adavijit** [comment]
@simranaggarwal1999  I wanted something like this https://github.com/adavijit/BlogMan/pull/136
For now I am merging his PR.  Try to make it better and then your PR will be merged

**Comment by simranaggarwal1999** [comment]
No problem

**Comment by rajatmw1999** [comment]
@simranaggarwal1999 there are some conflicts

**Pull request closed without merging**
