### PR TITLE
Added login/register components

### PR DESCRIPTION
**Pull request by sebasblancogonz**
Hello there again!

I've added both login and register components with a minimalistic design.
It's really simple when it comes to functionality.
- **Login**: Fetchs the user in the database (API call with axios), if exists, will generate a token for the given user and will save it in the local storage (both elements, user and token).
- **Register**: Just like login, but creates token after creating user. Saves both token and user in local storage.

When info is saved on localstorage, only the username is saved. Not his/her hashed password or ID.

I've also added a simple bootstrap navbar with a log out button.

You'll noticed I've refactored react's default folder structure.

Hope it fits!

### CODE REVIEW

**Comment by sebasblancogonz** [comment]
Btw I forgot to mention that I protected some urls, like "/". You can only access the main page if you are logged in.

**Comment by adavijit** [comment]
@sebasblancogonz  Great work! I will surely merge it. But can you please provide me a screenshot?

**Comment by sebasblancogonz** [comment]
Register
image
Login
image
Home
image

**Comment by sebasblancogonz** [comment]
Oh, the Sign Up form is a multistep form 
image

**Comment by sebasblancogonz** [comment]
You will have to start the server application first. The .ENV file on the front-end folder is pointing to the 3000 port. You can change it if you want, of course.

**Comment by adavijit** [comment]
@sebasblancogonz 
Have you connected your front end with your backend functionality?

**Comment by sebasblancogonz** [comment]
> @sebasblancogonz
> Have you connected your front end with your backend functionality?

That's right. It's fully working with the back-end functionality

**Comment by adavijit** [comment]
@sebasblancogonz  Great work! Merged! will look forward to working with you!

**Comment by adavijit** [comment]
@sebasblancogonz I appreciate your work! You can go for #8 or #7  if you wish to

**Pull request merged**
