### PR TITLE
UX for subjective quiz section

### LINKED ISSUE #145: Code the wireframe for SUBJECTIVE QUIZ section
The wireframe for SUBJECTIVE QUIZ section is stored at "\front-end\public\wire-frame\Quiz_Subjective .png".
Be sure to make the design responsive for mobile as well. This is just the header of the education section of blogman.

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Fixes #145 

Code of wireframe for Subjective Quiz Section
Snippet
image

image

@rajatmw1999 Kindly check

### CODE REVIEW

**Comment by adavijit** [comment]
@shreyakapoor08  please post a screenshot while raising a PR

**Comment by shreyakapoor08** [comment]
> @shreyakapoor08 please post a screenshot while raising a PR

@adavijit I have added the screenshots. Kindly check

**Comment by shreyakapoor08** [comment]
@rajatmw1999 Kindly review

**Comment by shreyakapoor08** [comment]
@adavijit Hi, is there any more correction required in this one?

**Comment by shreyakapoor08** [comment]
@adavijit Kindly review this PR

**Comment by shreyakapoor08** [comment]
@adavijit @rajatmw1999 Kindly review this PR, it's pending since very long!

**Pull request merged**
